### ISSUE TITLE
Output the assembly graph

### ISSUE THREAD

**Issue by tseemann** [ncbi/SKESA#5]
The assembly graph is very important to be able to reconstruct which contigs were near other contigs. This can be visualized in Bandage.

Ideally skesa would produce `contigs.gfa` (GFA2)

See https://github.com/GFA-spec/GFA-spec

**Comment by souvorov** [comment]
Yes, this is one of the things we are going to work on in the near future.

**Comment by sjackman** [comment]
Yes, please!

**Comment by souvorov** [comment]
Meanwhile I would like to mention that there is an option --allow_snps which is a small step in this direction.  With this option SKESA will make another round of kmer iterations. Instead of making a break at each fork it will follow every branch up to --max_snp_len base pairs. If all branches come together SKESA will remember all variants and will continue assembling. The most supported variant will be printed as contig. All other variants will be printed as short sequences with id Variant_X_for_Contig_Y:A_B:F where A/B are 1-based positions of the variant X on the contig Y. F is the relative weight of the variant.

This feature is useful for reconstructing ribosomal RNAs.  Below is 16S assembled from SRR1505904.
![16s](https://user-images.githubusercontent.com/26233366/46582031-32c6a700-ca0f-11e8-965c-1aff654a3343.jpg)

**Comment by souvorov** [comment]
There is a new executable which can connect SKESA or any other contigs into a GFA graph.

skesa --sra_run SRR1510963 --hash_count --contigs_out SRR1510963_skesa.fa >& SRR1510963_skesa.log

gfa_connector --sra_run SRR1510963 --contigs SRR1510963_skesa.fa --gfa SRR1510963.gfa --csv SRR1510963.csv --kmer 75 >& SRR1510963_gfa.log
